import { ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Profile } from "@/types/portfolio";
import FollowButton from "@/components/community/FollowButton";

interface HeroProps { userProfile: Profile; }
export default function Hero({ userProfile }: HeroProps) {
  const displayName = userProfile.name || userProfile.full_name || "Portfolio owner";
  return <section className="w-full py-16 md:py-24 px-6 md:px-12 lg:px-24 overflow-hidden"><div className="max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-2 gap-12 items-center"><div className="flex flex-col space-y-6 animate-fade-in"><p className="text-sm font-medium uppercase tracking-wider text-primary">Portfolio</p><h1 className="text-4xl md:text-5xl lg:text-6xl font-bold">Hi, I’m <span className="bg-clip-text text-transparent bg-gradient-to-r from-primary to-blue-500">{displayName}</span></h1>{userProfile.title && <h2 className="text-2xl md:text-3xl font-medium text-muted-foreground">{userProfile.title}</h2>}{userProfile.bio && <p className="text-lg max-w-md text-muted-foreground">{userProfile.bio}</p>}<div className="flex flex-col sm:flex-row gap-4 pt-4"><Button size="lg" asChild><a href="#projects" className="group">View projects<ArrowRight className="ml-2 h-4 w-4 group-hover:translate-x-1 transition-transform" aria-hidden="true" /></a></Button><Button size="lg" variant="outline" asChild><a href="#contact">Contact me</a></Button></div>{userProfile.id && <div className="pt-2"><FollowButton targetUserId={userProfile.id} showCount /></div>}</div><div className="relative rounded-2xl overflow-hidden h-64 md:h-96 bg-secondary shadow-xl flex items-center justify-center animate-scale-in">{(userProfile.avatarUrl || userProfile.avatar_url) ? <img src={userProfile.avatarUrl || userProfile.avatar_url} alt={displayName} className="w-full h-full object-cover" /> : <div className="hero-gradient w-full h-full flex items-center justify-center"><span className="text-7xl font-bold text-white" aria-hidden="true">{displayName.charAt(0).toUpperCase()}</span></div>}</div></div></section>;
}
