// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojpygyznnaxxoniqdmxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qcHlneXpubmF4eG9uaXFkbXhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3MjE2MzcsImV4cCI6MjA1OTI5NzYzN30.Ykxw3FygnBxOule-9S_cFSbMiwkDIN22Md8LvltkI34";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);